[profile.dev]
incremental = true
debug = 0

[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
# Minimum Rust version
rust-version = "1.78"

[workspace.dependencies]
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
serde_yaml = "0.9.34"
anyhow = { version = "1.0.86", features = ["backtrace"] }
tokio = { version = "1.38.0", features = ["full"] }
tokio-util = { version = "0.7.11", features = ["full"] }
async-openai = "0.21.0"
async-trait = "0.1.80"
url = "2.5.0"
indoc = "2.0.5"
reqwest = { version = "0.12.4" }
futures-util = "0.3.30"
once_cell = "1.19.0"
dotenvy = "0.15.7"
regex = "1.10.4"
rand = "0.8.5"
askama = "0.12.1"
uuid = { version = "1.8.0", features = ["v4", "serde"] }
shell-escape = "0.1.5"
octocrab = "0.38.0"
strum = { version = "0.26.2", features = ["derive"] }
strum_macros = "0.26.2"
redis = { version = "0.25.4", features = [
    "aio",
    "tokio-comp",
    "connection-manager",
    "tokio-rustls-comp",
] }
derive_builder = "0.20.0"

# Web
axum = { version = "0.7.5", features = [
    "multipart",
    "tracing",
    "ws",
    "macros",
] }
tower-http = { version = "0.5.2", features = ["trace", "limit"] }

# Testing
test-log = { version = "0.2.16", default-features = false, features = [
    "trace",
] }
wiremock = { version = "0.6.0" }
mockall = { version = "0.12.1" }

# CLI
clap = { version = "4.5.4", features = ["derive"] }
spinners = { version = "4.1.1" }

# Websockets
tokio-tungstenite = { version = "0.21.0" }

# Telemetry
opentelemetry = "0.23.0"
opentelemetry_sdk = { version = "0.23.0", features = ["rt-tokio"] }
opentelemetry-stdout = { version = "0.4.0", features = ["trace"] }
tracing-opentelemetry = "0.24.0"
opentelemetry-otlp = { version = "0.16.0", features = [
    "http-proto",
    "reqwest-client",
    "reqwest-rustls",
] }
tracing = { version = "0.1.40", features = ["log"] }
tracing-subscriber = { version = "0.3.18", features = [
    "env-filter",
    "ansi",
    "json",
] }
itertools = { version = "0.13.0" }
qdrant-client = { version = "1.9.0" }
chrono = { version = "0.4.38" }
