[workspace]
changelog_update = false
changelog_path = "./CHANGELOG.md"
changelog_config = "cliff.toml"
git_tag_name = "v{{ version }}"
git_tag_enable = false
git_release_enable = false

[[package]]
# Only release the main package on github
name = "swiftide"
git_tag_name = "v{{ version }}"
git_tag_enable = true
git_release_enable = true
changelog_include = [
  "swiftide-core",
  "swiftide-indexing",
  "swiftide-integrations",
  "swiftide-query",
  "swiftide-test-utils",
]
changelog_update = true
