[workspace]
changelog_update = false
git_tag_enable = false
git_release_enable = false
changelog_config = "../cliff.toml"

[[package]]
# Only release the main package on github
name = "swiftide"
git_tag_name = "v{{ version }}"
git_tag_enable = true
git_release_enable = true
changelog_path = "../CHANGELOG.md"
changelog_update = true
changelog_include = ["swiftide-*"]
